version: "3.9"

services: 
    database: 
        image: postgres
        container_name: database
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=nodejs
            - POSTGRES_DB=leoo-challenge
        volumes: 
            - pgdata:/data/postgres
    app:
        build: .
        container_name: back-end-challenge
        restart: always
        ports: 
            - 3333:3333
        volumes: 
            - .:/usr/app
        links:
            - database
        depends_on: 
            - database

volumes: 
    pgdata: 
        driver: local